[package]
name = "rusty-docker"
version = "0.1.0"
authors = ["James Casey <james@chef.io>"]

[dependencies]
clap = "2.31"
nix = "0.10.0"
uuid = { version = "0.6.2", features = ["v4"]}
tar = "0.4"
lazy_static = "1.0.0"

