#!/usr/bin/env bash
#
# The dirtiest cleanup script
#

# don't interfere with umount
pushd /

# umount stuff
while $(grep -q containers /proc/mounts); do 
    sudo umount $(grep containers /proc/mounts | shuf | head -n1 | cut -f2 -d' ') 2>/dev/null
done

popd

# remove stuff
sudo rm -rf ./containers/*

